# pixi-toolchain.cmake
if (NOT DEFINED ENV{PIXI_ENV_PATH})
	message(FATAL_ERROR "Pixi environment not set")
endif()
if(NOT EXISTS "$ENV{PIXI_ENV_PATH}")
	message(FATAL_ERROR "Pixi environment not found at $ENV{PIXI_ENV_PATH}")
endif()

set(CMAKE_SYSROOT "$ENV{PIXI_ENV_PATH}")
set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
message(WARNING "CMAKE_SYSROOT: ${CMAKE_SYSROOT}")

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
